@tool
extends EditorScript

func _run():
	var profile = SkeletonProfileHumanoid.new()

	# HumanCrafting BoneMap
	var humancraft = BoneMap.new()
	humancraft.profile = profile
	humancraft.set_skeleton_bone_name("Root", "B-root")
	humancraft.set_skeleton_bone_name("Hips", "B-hips")
	humancraft.set_skeleton_bone_name("Spine", "B-spine")
	humancraft.set_skeleton_bone_name("Chest", "B-chest")
	humancraft.set_skeleton_bone_name("UpperChest", "")
	humancraft.set_skeleton_bone_name("Neck", "B-neck")
	humancraft.set_skeleton_bone_name("Head", "B-head")
	humancraft.set_skeleton_bone_name("LeftShoulder", "B-shoulder.L")
	humancraft.set_skeleton_bone_name("LeftUpperArm", "B-upperArm.L")
	humancraft.set_skeleton_bone_name("LeftLowerArm", "B-forearm.L")
	humancraft.set_skeleton_bone_name("LeftHand", "B-hand.L")
	humancraft.set_skeleton_bone_name("RightShoulder", "B-shoulder.R")
	humancraft.set_skeleton_bone_name("RightUpperArm", "B-upperArm.R")
	humancraft.set_skeleton_bone_name("RightLowerArm", "B-forearm.R")
	humancraft.set_skeleton_bone_name("RightHand", "B-hand.R")
	humancraft.set_skeleton_bone_name("LeftUpperLeg", "B-thigh.L")
	humancraft.set_skeleton_bone_name("LeftLowerLeg", "B-shin.L")
	humancraft.set_skeleton_bone_name("LeftFoot", "B-foot.L")
	humancraft.set_skeleton_bone_name("LeftToes", "B-toe.L")
	humancraft.set_skeleton_bone_name("RightUpperLeg", "B-thigh.R")
	humancraft.set_skeleton_bone_name("RightLowerLeg", "B-shin.R")
	humancraft.set_skeleton_bone_name("RightFoot", "B-foot.R")
	humancraft.set_skeleton_bone_name("RightToes", "B-toe.R")
	ResourceSaver.save(humancraft, "res://retarget/humancraft_bonemap.tres")
	print("Saved humancraft_bonemap.tres")

	# Toon City People BoneMap
	var toon = BoneMap.new()
	toon.profile = profile
	toon.set_skeleton_bone_name("Root", "Root")
	toon.set_skeleton_bone_name("Hips", "Hips")
	toon.set_skeleton_bone_name("Spine", "Spine_01")
	toon.set_skeleton_bone_name("Chest", "Spine_02")
	toon.set_skeleton_bone_name("UpperChest", "Spine_03")
	toon.set_skeleton_bone_name("Neck", "Neck")
	toon.set_skeleton_bone_name("Head", "Head")
	toon.set_skeleton_bone_name("LeftShoulder", "Clavicle.L")
	toon.set_skeleton_bone_name("LeftUpperArm", "Arm.L")
	toon.set_skeleton_bone_name("LeftLowerArm", "Forearm.L")
	toon.set_skeleton_bone_name("LeftHand", "Hand.L")
	toon.set_skeleton_bone_name("RightShoulder", "Clavicle.R")
	toon.set_skeleton_bone_name("RightUpperArm", "Arm.R")
	toon.set_skeleton_bone_name("RightLowerArm", "Forearm.R")
	toon.set_skeleton_bone_name("RightHand", "Hand.R")
	toon.set_skeleton_bone_name("LeftUpperLeg", "Quad.L")
	toon.set_skeleton_bone_name("LeftLowerLeg", "Shin.L")
	toon.set_skeleton_bone_name("LeftFoot", "Foot.L")
	toon.set_skeleton_bone_name("LeftToes", "Toes.L")
	toon.set_skeleton_bone_name("RightUpperLeg", "Quad.R")
	toon.set_skeleton_bone_name("RightLowerLeg", "Shin.R")
	toon.set_skeleton_bone_name("RightFoot", "Foot.R")
	toon.set_skeleton_bone_name("RightToes", "Toes.R")
	ResourceSaver.save(toon, "res://retarget/toon_bonemap.tres")
	print("Saved toon_bonemap.tres")
